#!/bin/bash
source ../Utils/set_env_script

# mkdir -p $preprocessed_dir
# for subject in 1; do
#     mkdir -p $preprocessed_dir/imagenet40-1000-$subject
# done

# cd /d/Data/CVPR2021-02785/CVPR2021-02785/code/TeamX_code

# matlab -nosplash -nodesktop -r "run('D:\Data\CVPR2021-02785\CVPR2021-02785\code\TeamX_code\preprocessing.m');"

python split_even_index_60_percent.py -iv image -s big -in "$EEG_SEGMENTS_DIR" -out "$TORCH_MODEL_FILE" -stimuli "$STIMULI_TEXT" -f 5